# Generated by Django 5.2.17 on 2026-10-05 03:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, unique=True)),
                ('title', models.CharField(blank=True, max_length=80)),
                ('mode', models.CharField(choices=[('approval', 'Host approval'), ('open', 'Open floor')], default='approval', max_length=10)),
                ('speaker_limit', models.PositiveSmallIntegerField(default=10)),
                ('host_key_hash', models.CharField(max_length=64)),
                ('version', models.PositiveIntegerField(default=0)),
                ('ended', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(max_length=32)),
                ('secret_hash', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=40)),
                ('is_host', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('listener', 'Listener'), ('speaker', 'Speaker')], default='listener', max_length=10)),
                ('role_since', models.DateTimeField(default=django.utils.timezone.now)),
                ('queued_at', models.DateTimeField(blank=True, null=True)),
                ('connected', models.BooleanField(default=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('banned', models.BooleanField(default=False)),
                ('last_event_ts', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='rooms.room')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('room', 'identity'), name='uniq_room_identity'), models.UniqueConstraint(fields=('room', 'secret_hash'), name='uniq_room_secret')],
            },
        ),
    ]
