# Generated by Django 5.2.17 on 2026-10-05 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='last_event_ts',
            new_name='session_joined_at',
        ),
        migrations.AddField(
            model_name='participant',
            name='livekit_sid',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
