# Generated by Django 5.2.17 on 2026-10-05 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_rename_last_event_ts_participant_session_joined_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
