# Generated by Django 5.2.17 on 2026-10-07 11:59

import django.db.models.deletion
import django.utils.timezone
from django.db.models import F
from django.db import migrations, models


def set_ended_at_for_existing_rooms(apps, schema_editor):
    Room = apps.get_model("rooms", "Room")
    Room.objects.filter(ended=True, ended_at__isnull=True).update(ended_at=F("ends_at"))


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_room_screen_share_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='blocked_from_questions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='anonymous_questions_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(set_ended_at_for_existing_rooms, migrations.RunPython.noop),
        migrations.AddField(
            model_name='room',
            name='questions_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('kind', models.CharField(choices=[('question', 'Question'), ('suggestion', 'Suggestion')], max_length=10)),
                ('anonymous', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('answered', 'Answered'), ('dismissed', 'Dismissed')], default='pending', max_length=10)),
                ('deleted_by_sender', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='rooms.room')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='rooms.participant')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('anonymous', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='rooms.room')),
                ('question', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcement', to='rooms.question')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['room', 'status', 'created_at'], name='rooms_quest_room_id_498557_idx'),
        ),
    ]
